[project]
name = "nc-streaming-data-project"
version = "0.1.0"
description = "Guardian API data streaming tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.4",
    "safety>=3.3.1",
]
